# Generated by Django 4.2.7 on 2023-11-27 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(to='myapp.skill'),
        ),
    ]
